/**
 * Image Generation Service
 * Supports both local GPU (Stable Diffusion) and cloud APIs
 */

/**
 * Generate image using local GPU (Stable Diffusion via AUTOMATIC1111 API)
 * Requires Stable Diffusion WebUI running on http://localhost:7860
 */
export const generateImageLocal = async (prompt: string): Promise<string> => {
  const sdApiUrl = process.env.VITE_SD_API_URL || "http://localhost:7860";

  // Enhanced prompt for cybersecurity themes
  const enhancedPrompt = `
${prompt},
professional cybersecurity illustration, modern tech aesthetic,
dark blue and cyan color scheme, abstract digital security concept,
network visualization, security operations center vibe,
high quality, detailed, 16:9 aspect ratio, no text, no labels
`;

  const negativePrompt = `
text, words, letters, labels, logos, watermark, signature,
low quality, blurry, distorted, amateur, cartoon, anime
`;

  try {
    const response = await fetch(`${sdApiUrl}/sdapi/v1/txt2img`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        prompt: enhancedPrompt,
        negative_prompt: negativePrompt,
        steps: 30,
        width: 1024,
        height: 576, // 16:9 ratio
        cfg_scale: 7,
        sampler_name: "DPM++ 2M Karras",
        seed: -1,
      }),
    });

    if (!response.ok) {
      throw new Error(`SD API returned ${response.status}: ${await response.text()}`);
    }

    const data = await response.json();

    if (!data.images || data.images.length === 0) {
      throw new Error("No images generated by Stable Diffusion");
    }

    // Return as data URL
    return `data:image/png;base64,${data.images[0]}`;
  } catch (error) {
    console.error("Local image generation failed:", error);
    throw new Error(
      `Failed to generate image locally. Make sure Stable Diffusion WebUI is running on ${sdApiUrl}. Error: ${error}`
    );
  }
};

/**
 * Check if local SD API is available
 */
export const isLocalSDAvailable = async (): Promise<boolean> => {
  const sdApiUrl = process.env.VITE_SD_API_URL || "http://localhost:7860";

  try {
    const response = await fetch(`${sdApiUrl}/sdapi/v1/sd-models`, {
      method: "GET",
      signal: AbortSignal.timeout(3000), // 3 second timeout
    });
    return response.ok;
  } catch (error) {
    return false;
  }
};

/**
 * Get status of local Stable Diffusion setup
 */
export const getLocalSDStatus = async (): Promise<{
  available: boolean;
  models?: string[];
  error?: string;
}> => {
  const sdApiUrl = process.env.VITE_SD_API_URL || "http://localhost:7860";

  try {
    const response = await fetch(`${sdApiUrl}/sdapi/v1/sd-models`, {
      method: "GET",
      signal: AbortSignal.timeout(3000),
    });

    if (!response.ok) {
      return {
        available: false,
        error: `SD API returned status ${response.status}`,
      };
    }

    const models = await response.json();
    return {
      available: true,
      models: models.map((m: any) => m.title || m.model_name),
    };
  } catch (error) {
    return {
      available: false,
      error: error instanceof Error ? error.message : "Connection failed",
    };
  }
};
